name: Base Deploy

on:
  workflow_call:
    inputs:
      AWS_ACCESS_KEY_ID_S3:
        type: string
        required: true
      EKS_CLUSTER:
        type: string
        required: true
      PROJECT_NAME:
        type: string
        required: true
      GIT_SHA:
        type: string
        required: true
      GIT_BRANCH:
        type: string
        required: true
      WP_API_VERSION:
        type: string
        required: true
      WP_WEB_VERSION:
        type: string
        required: true
      WP_ENVIRONMENT:
        type: string
        required: true
      WP_DOMAIN:
        type: string
        required: true
      SMTP_USERNAME:
        type: string
        required: false
      WP_K8S_VERSION:
        type: string
        required: false

    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SECRET_ACCESS_KEY_S3:
        required: true
      RAILS_MASTER_KEY:
        required: true
      REDIS_PASSWORD:
        required: true
      DATABASE_PASSWORD:
        required: true
      GIT_ACCESS_TOKEN:
        required: true
      SMTP_PASSWORD:
        required: false
      DB_MASTER_PASSWORD:
        required: false
      HUBSPOT_WORKPATH_ACCESS_TOKEN:
        required: true
      TABLEAU_ADMIN_PASSWORD:
        required: true

env:
  AWS_DEFAULT_REGION: eu-central-1

jobs:
  base_deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.WP_ENVIRONMENT }}
    steps:
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Set EKS context for Kubectl
        run: |
          aws eks --region ${{ env.AWS_DEFAULT_REGION }} update-kubeconfig --name ${{ inputs.EKS_CLUSTER }}

      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/WorkpathHQ/workpath_k8s/releases/latest
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}

      - id: latest_release_tag
        run: latestReleaseTag=$(echo $RESULT | jq | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/')
          echo "latest_release_tag=$latestReleaseTag" >> $GITHUB_OUTPUT

      - name: Replace k8s Version when provided
        # Added so a k8s version can be optionally chosen. If no k8s version is provided in the inputs, uses the version in env.
        id: k8sVersion
        run: |
          k8sVersion=${{ inputs.WP_K8S_VERSION }}
          echo "k8sVersion=${k8sVersion:=${{ steps.latest_release_tag.outputs.latest_release_tag }}}" >> $GITHUB_OUTPUT
        

      - name: Clone workpath_k8s repository
        uses: actions/checkout@v3
        with:
          repository: WorkpathHQ/workpath_k8s
          ref: ${{ steps.k8sVersion.outputs.k8sVersion }}
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          path: ${{ github.workspace }}/workpath_k8s
          fetch-depth: 0

      - name: Deploying
        # Added if else to differentiate between the environments
        run: |
          cd ${{ github.workspace }}/workpath_k8s/workpath_app
          ./envsubst-multi.sh && source ./envsubst-multi.sh
          echo "$(tr '[:lower:]' '[:upper:]' <<< ${{ inputs.WP_ENVIRONMENT }}) env will be reachable via $WP_SUBDOMAIN.admin.$WP_DOMAIN, $WP_SUBDOMAIN.api.$WP_DOMAIN, $WP_SUBDOMAIN.hooli.$WP_DOMAIN"
          kubectl apply -k overlays/${{ inputs.WP_ENVIRONMENT }}
          if [ ${{ inputs.WP_ENVIRONMENT }} == qa ]; then
            kubectl rollout status deploy workpath-api -n $WP_SUBDOMAIN --timeout=400s
          else
            kubectl -n workpath-${{ inputs.WP_ENVIRONMENT }} rollout restart deployment workpath-api workpath-cronjobs workpath-sidekiq workpath-sidekiq-graph workpath-sidekiq-integrations
            kubectl -n workpath-${{ inputs.WP_ENVIRONMENT }} rollout status deploy workpath-api --timeout=900s
          fi

          echo "Succesful Deploy on $(tr '[:lower:]' '[:upper:]' <<< {{ inputs.WP_ENVIRONMENT }}), reachable via $WP_SUBDOMAIN.admin.$WP_DOMAIN, $WP_SUBDOMAIN.api.$WP_DOMAIN, $WP_SUBDOMAIN.connect.$WP_DOMAIN, *.$WP_DOMAIN"

        # Workaround for setting inputs as environmental variables (https://github.com/actions/runner/issues/665#issuecomment-699481628)
        env:
          PROJECT_NAME: ${{ inputs.PROJECT_NAME }}
          GIT_SHA: ${{ inputs.GIT_SHA }}
          GIT_BRANCH: ${{ inputs.GIT_BRANCH }}
          WP_API_VERSION: ${{ inputs.WP_API_VERSION }}
          WP_WEB_VERSION: ${{ inputs.WP_WEB_VERSION }}
          WP_ENVIRONMENT: ${{ inputs.WP_ENVIRONMENT }}
          AWS_ACCESS_KEY_ID_S3: ${{ inputs.AWS_ACCESS_KEY_ID_S3 }}
          WP_DOMAIN: ${{ inputs.WP_DOMAIN }}
          SMTP_USERNAME: ${{ inputs.SMTP_USERNAME }}
          AWS_SECRET_ACCESS_KEY_S3: ${{ secrets.AWS_SECRET_ACCESS_KEY_S3 }}
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          DB_MASTER_PASSWORD: ${{ secrets.DB_MASTER_PASSWORD }}
          HUBSPOT_WORKPATH_ACCESS_TOKEN: ${{ secrets.HUBSPOT_WORKPATH_ACCESS_TOKEN }}
          TABLEAU_ADMIN_PASSWORD: ${{ secrets.TABLEAU_ADMIN_PASSWORD }}
