name: Base Build image

on: 
  workflow_call:
    inputs:
      ECR_REPOSITORY:
        type: string
        required: true
      IMAGE_TAG:
        type: string
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

env:
  AWS_DEFAULT_REGION: eu-central-1
  ECR_REGISTRY: 147753604753.dkr.ecr.eu-central-1.amazonaws.com

jobs:
  base_build_image:
    name: Build image
    runs-on: 8-cores
    steps:
      - name: Check out code
        uses: actions/checkout@v5
     
      - uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to AWS ECR
        run: |
          docker build --tag ${{ env.ECR_REGISTRY }}/${{ inputs.ECR_REPOSITORY }}:${{ inputs.IMAGE_TAG }} .
          docker push ${{ env.ECR_REGISTRY }}/${{ inputs.ECR_REPOSITORY }}:${{ inputs.IMAGE_TAG }}   
