name: Delete QA namespaces when redeployed

on:
  workflow_call:
    inputs:
      BRANCH_NAME:
        type: string
        required: true
      EKS_CLUSTER:
        type: string
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

env:
  AWS_DEFAULT_REGION: eu-central-1

jobs:
  delete_namespaces_from_git-branch:
    name: Delete QA namespaces with GitBranch
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Set EKS staging context for Kubectl
        run: |
          aws eks --region ${{ env.AWS_DEFAULT_REGION }} update-kubeconfig --name wp-staging
          
      - name: Delete Namespaces with Git-branch label for PR
        run: |
          export gitLabel=$(echo ${{ inputs.BRANCH_NAME }} | tr '[:upper:]' '[:lower:]' | sed "s/\//-/g" | sed "s/\_/-/g" | sed "s/\./-/g" | cut -c1-54 | sed 's/\(.*\)-/\1/')
          kubectl delete namespaces -l git-branch=$gitLabel
          echo $gitLabel
