name: Prologue

on: 
  workflow_call:
    secrets:
      GIT_ACCESS_TOKEN:
        required: true

    outputs:
      GIT_PROJECT_NAME: 
        description: "Git project name"
        value: ${{ jobs.prologue.outputs.GIT_PROJECT_NAME }}
      GIT_BRANCH: 
        description: "Branch name"
        value: ${{ jobs.prologue.outputs.GIT_BRANCH }}
      GIT_SHORTENED_BRANCH: 
        description: "Cleaned branch name"
        value: ${{ jobs.prologue.outputs.GIT_SHORTENED_BRANCH }}
      GIT_SHA: 
        description: "Full GitHub Sha"
        value: ${{ jobs.prologue.outputs.GIT_SHA }}
      GIT_SHORT_SHA: 
        description: "Short GitHub sha"
        value: ${{ jobs.prologue.outputs.GIT_SHORT_SHA }}
      GIT_COMMIT_AUTHOR_SUBJECT: 
        description: "Author + Last commit / PR title"
        value: ${{ jobs.prologue.outputs.GIT_COMMIT_AUTHOR_SUBJECT }}
      WP_API_VERSION:
        description: "Contains the current SHA of the master branch of the API repo"
        value: ${{ jobs.prologue.outputs.WP_API_VERSION }}
      WP_WEB_VERSION:
        description: "Contains the current SHA of the master branch of the WEB repo"
        value: ${{ jobs.prologue.outputs.WP_WEB_VERSION }}

jobs:
  prologue:
    name: Prologue
    environment: ${{ inputs.WP_ENVIRONMENT }}
    runs-on: ubuntu-latest
    outputs:
      GIT_PROJECT_NAME: ${{ steps.vars.outputs.git_project_name }}
      GIT_BRANCH: ${{ steps.vars.outputs.git_branch }}
      GIT_SHORTENED_BRANCH: ${{ steps.vars.outputs.git_shortened_branch }}
      GIT_SHA: ${{ steps.vars.outputs.git_sha }}
      GIT_SHORT_SHA: ${{ steps.vars.outputs.git_short_sha }}
      GIT_COMMIT_AUTHOR_SUBJECT: ${{ steps.vars.outputs.git_commit_author_subject }}
      WP_API_VERSION: ${{ steps.vars.outputs.wp_api_version }}
      WP_WEB_VERSION: ${{ steps.vars.outputs.wp_web_version }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
     
      - name: Set outputs
        id: vars
        # Added condition to differentiate the trigger of the workflow ('workflow_dispatch', 'pull_request')
        run: |
          cd ${{ github.workspace }}
          git fetch
          GIT_PROJECT_NAME=${{ github.event.repository.name }}
          if [ ${{ github.event_name }} == "pull_request" ]; then
            GIT_REFERENCE=${{ github.head_ref }}
            GIT_SHA=${{ github.event.pull_request.base.sha }}
            git checkout master
          else 
            GIT_REFERENCE=${{ github.ref }}
            GIT_SHA=${{ github.sha }}
            git checkout $GIT_SHA
          fi
          GIT_BRANCH=$(echo ${GIT_REFERENCE#refs/heads/})
          GIT_SHORTENED_BRANCH=$(echo "$GIT_BRANCH" | tr '[:upper:]' '[:lower:]' | sed "s/\//-/g" | sed "s/\_/-/g" | sed "s/\./-/g" | cut -c1-54 | sed 's/\(.*\)-/\1/')
          GIT_SHORT_SHA=$(echo $GIT_SHA | cut -c1-7)
          WP_SUBDOMAIN="$GIT_SHORTENED_BRANCH-$GIT_SHORT_SHA"
          GIT_COMMIT_AUTHOR_SUBJECT=$(git show -s --format='%an %s')
          echo "git_project_name=$GIT_PROJECT_NAME" >> $GITHUB_OUTPUT
          echo "git_branch=$GIT_BRANCH" >> $GITHUB_OUTPUT
          echo "git_shortened_branch=$GIT_SHORTENED_BRANCH" >> $GITHUB_OUTPUT
          echo "git_sha=$GIT_SHA" >> $GITHUB_OUTPUT
          echo "git_short_sha=$GIT_SHORT_SHA" >> $GITHUB_OUTPUT
          echo "wp_subdomain=$WP_SUBDOMAIN" >> $GITHUB_OUTPUT
          echo "git_commit_author_subject=$GIT_COMMIT_AUTHOR_SUBJECT" >> $GITHUB_OUTPUT

      - name: Get API SHA
        uses: actions/checkout@v3
        with:
          repository: WorkpathHQ/workpath_api
          ref: master
          token: ${{ secrets.GIT_ACCESS_TOKEN }}

      - name: Set Output
        run: |
          LATEST_SHORT_SHA=$(git rev-parse HEAD | cut -c1-7)
          echo $LATEST_SHORT_SHA
          echo "wp_api_version=$(echo $LATEST_SHORT_SHA)" >> $GITHUB_OUTPUT
      
      - name: Get WEB SHA
        uses: actions/checkout@v3
        with:
          repository: WorkpathHQ/workpath_web
          ref: master
          token: ${{ secrets.GIT_ACCESS_TOKEN }}

      - name: Set Output
        run: |
          LATEST_SHORT_SHA=$(git rev-parse HEAD | cut -c1-7)
          echo $LATEST_SHORT_SHA
          echo "wp_web_version=$(echo $LATEST_SHORT_SHA)" >> $GITHUB_OUTPUT