name: Slack notification

on: 
  workflow_call:
    inputs:
      payload-file-name:
        type: string
        required: true
      GIT_PROJECT_NAME:
        type: string
        required: true
      GIT_SHA:
        type: string
        required: true
      GIT_COMMIT_AUTHOR_SUBJECT:
        type: string
        required: true
      WP_DOMAIN: 
        type: string
        required: true
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
      GIT_ACCESS_TOKEN:
        required: true

jobs:
  send_slack_notification:
    name: Send Slack notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: WorkpathHQ/github_action_cicd
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          path: ${{ github.workspace }}/github_action_cicd
          ref: slacktest

      

      - name: readJson
        id: readJson
        run: |
          export GIT_SERVER_URL=${{ github.server_url }}
          export GIT_PROJECT_NAME=${{ inputs.GIT_PROJECT_NAME }}
          export GIT_REPOSITORY=${{ github.repository }}
          export GIT_RUN_ID=${{ github.run_id }}
          export GIT_TRIGGERING_ACTOR=${{ github.triggering_actor }} 
          export GIT_SHA=${{ inputs.GIT_SHA }}
          export GIT_SHORT_SHA=$(echo $GIT_SHA | cut -c1-7)
          export GIT_COMMIT_AUTHOR_SUBJECT=${{ inputs.GIT_COMMIT_AUTHOR_SUBJECT }}
          export WP_DOMAIN=${{ inputs.WP_DOMAIN }}
          FILE_PATH=${{ github.workspace }}/github_action_cicd/payloads/${{ inputs.payload-file-name }}
          mkdir ./tmp
          # awk removes the indents
          # tr removes the newlines but somehow leaves '\n'
          cat $FILE_PATH | awk '{$1=$1};1' | tr '\n' ' ' > ./tmp/trimmed.json

          content=$(envsubst < ./tmp/trimmed.json)
          rm -r ./tmp
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
         
          echo "::set-output name=packageJson::$content"

      - name: Send Json via curl
        run: | 
          curl -X POST $SLACK_WEBHOOK_URL -H "Content-Type: application/json" -d '${{ steps.readJson.outputs.packageJson }}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          



