name: Slack notification

on:
  workflow_call:
      inputs:
        SLACK_PAYLOAD:
          type: string
          required: true
      secrets:
        SLACK_WEBHOOK_URL:
          required: true

jobs:
  slack_notification:
    name: Send Slack notification
    runs-on: ubuntu-latest
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        # https://github.com/marketplace/actions/slack-send
        uses: slackapi/slack-github-action@v1.21.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: ${{ inputs.SLACK_PAYLOAD }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
