name: Slack notification

on: 
  workflow_call:
    inputs:
      payload-file-path:
        type: string
        required: true
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
      GIT_ACCESS_TOKEN:
        required: true

jobs:
  send_slack_notification:
    name: Send Slack notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: WorkpathHQ/github_action_cicd
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          path: ${{ github.workspace }}/github_action_cicd
          ref: slacktest

      - name: readJson
        id: readJson
        run: |
          content=$(cat ${{ inputs.payload-file-path }})
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=packageJson::$content"

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": " *'${{ needs.prologue.outputs.GIT_PROJECT_NAME }}'* \n <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} | new stack> created by ${{ github.triggering_actor }} \n <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.event.pull_request.head.sha }} | ${{ needs.prologue.outputs.GIT_SHORT_SHA }}> | ${{ needs.prologue.outputs.GIT_COMMIT_AUTHOR_SUBJECT }} \n <https://${{ env.WP_DOMAIN }}.admin.workpath.dev|Admin Panel> | admin@workpath.com \n <https://${{ env.WP_DOMAIN }}.hooli.workpath.dev|Login Page> | demo+admin1@workpath.com \n <https://${{ env.WP_DOMAIN }}.connect.workpath.dev|Connect URL> \n <https://workpath.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-workpath-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22$WP_DOMAIN%5C%22%7D%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D|Grafana> | Application Logs"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
