name: Slack notification

on: 
  workflow_call:
    inputs:
      payload-file-path:
        type: string
        required: true
      GIT_PROJECT_NAME:
        type: string
        required: true
      GIT_SHA:
        type: string
        required: true
      GIT_COMMIT_AUTHOR_SUBJECT:
        type: string
        required: true
      WP_DOMAIN: 
        type: string
        required: true
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
      GIT_ACCESS_TOKEN:
        required: true

jobs:
  send_slack_notification:
    name: Send Slack notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: WorkpathHQ/github_action_cicd
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          path: ${{ github.workspace }}/github_action_cicd
          ref: slacktest

      

      - name: readJson
        id: readJson
        run: |
          export GIT_SERVER_URL=${{ github.server_url }}
          export GIT_PROJECT_NAME=${{ inputs.GIT_PROJECT_NAME }}
          export GIT_REPOSITORY=${{ github.repository }}
          export GIT_RUN_ID=${{ github.run_id }}
          export GIT_TRIGGERING_ACTOR=${{ github.triggering_actor }} 
          export GIT_SHA=${{ inputs.GIT_SHA }}
          export GIT_SHORT_SHA=$(echo $GIT_SHA | cut -c1-7)
          export GIT_COMMIT_AUTHOR_SUBJECT=${{ inputs.GIT_COMMIT_AUTHOR_SUBJECT }}
          export WP_DOMAIN=${{ inputs.WP_DOMAIN }}

          mkdir ./tmp

          cat ${{ github.workspace }}/github_action_cicd/payloads/payloadText.txt | tr '\n' ' ' > ./tmp/trimmed.txt
          echo "Trimmed Text:"
          echo $(cat ./tmp/trimmed.txt)

          export TEXT=$(envsubst < ./tmp/trimmed.txt)

          echo "Text:""
          echo $TEXT

          content=$(envsubst < ${{ inputs.payload-file-path }})

          echo "Content:"
          echo $content

          echo "::set-output name=packageJson::$content"

      # https://github.com/alonsohki/slack-webhook-payload
      - uses: alonsohki/slack-webhook-payload@v1
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          content: ${{ steps.readJson.outputs.packageJson }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          WP_DOMAIN: workpath.dev
