name: Base Deploy 

on: 
  workflow_call:
    inputs:
      AWS_ACCESS_KEY_ID_S3:
        type: string
        required: true
      EKS_CLUSTER:
        type: string
        required: true
      PROJECT_NAME:
        type: string
        required: true
      GIT_SHA:
        type: string
        required: true
      GIT_BRANCH:
        type: string
        required: true
      WP_API_VERSION:
        type: string
        required: true
      WP_WEB_VERSION:
        type: string
        required: true
      WP_ENVIRONMENT:
        type: string
        required: true
      WP_DOMAIN:
        type: string
        required: true
      SMTP_USERNAME:
        type: string
        required: false
      WP_K8S_VERSION:
        type: string
        required: false

    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SECRET_ACCESS_KEY_S3:
        required: true     
      RAILS_MASTER_KEY:
        required: true
      SIDEKIQ_CACHE_PASSWORD:
        required: true
      FRAGMENT_CACHE_PASSWORD:
        required: true
      FLIPPER_CACHE_PASSWORD:
        required: true
      DATABASE_PASSWORD:
        required: true
      GIT_ACCESS_TOKEN:
        required: true
      SMTP_PASSWORD:
        required: false


env: 
  AWS_DEFAULT_REGION: eu-central-1

jobs:     
  base_deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Set EKS context for Kubectl
        run: |
          aws eks --region ${{ env.AWS_DEFAULT_REGION }} update-kubeconfig --name ${{ inputs.EKS_CLUSTER }}
          
      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/WorkpathHQ/workpath_k8s/releases/latest
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}

      - id: latest_release_tag
        run: |
          latestReleaseTag=$(echo $RESULT | jq | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/')
          echo "latest_release_tag=$latestReleaseTag" >> $GITHUB_OUTPUT
        env:
          RESULT: ${{ steps.get_latest_release.outputs.data }}

      - name: Replace k8s Version when provided
        # Added so a k8s version can be optionally chosen. If no k8s version is provided in the inputs, uses the version in env.
        id: k8sVersion
        run: |
          k8sVersion=${{ inputs.WP_K8S_VERSION }}
          echo "k8sVersion=${k8sVersion:=${{ steps.latest_release_tag.outputs.latest_release_tag }}}" >> $GITHUB_OUTPUT

      - name: Clone workpath_k8s repository
        uses: actions/checkout@v3
        with:
          repository: WorkpathHQ/workpath_k8s
          ref: ${{ steps.k8sVersion.outputs.k8sVersion }}
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          path: ${{ github.workspace }}/workpath_k8s

      - name: Deploying
      # Added if else to differentiate between the environments
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl
          sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
          echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
          sudo apt-get install -y kubectl=1.23.17-00
          cd ${{ github.workspace }}/workpath_k8s/workpath_app
          ./envsubst-multi.sh && source ./envsubst-multi.sh
          echo "$(tr '[:lower:]' '[:upper:]' <<< ${{ inputs.WP_ENVIRONMENT }}) env will be reachable via $WP_SUBDOMAIN.admin.$WP_DOMAIN, $WP_SUBDOMAIN.api.$WP_DOMAIN, $WP_SUBDOMAIN.hooli.$WP_DOMAIN"
          if [ ${{ inputs.WP_ENVIRONMENT }} == qa ]; then
            kubectl apply -k overlays/${{ inputs.WP_ENVIRONMENT }}
            kubectl rollout status deploy workpath-web -n $WP_SUBDOMAIN --timeout=0s
            kubectl rollout status deploy workpath-api -n $WP_SUBDOMAIN --timeout=300s
          else 
            kubectl apply -k overlays/${{ inputs.WP_ENVIRONMENT }} --selector "app in (workpath-ns, workpath-web)"
            kubectl -n workpath-${{ inputs.WP_ENVIRONMENT }} rollout restart deployment workpath-web
            kubectl -n workpath-${{ inputs.WP_ENVIRONMENT }} rollout status deploy workpath-web --timeout=0s
          fi
          echo "Succesful Deploy on $(tr '[:lower:]' '[:upper:]' <<< {{ inputs.WP_ENVIRONMENT }}), reachable via $WP_SUBDOMAIN.admin.$WP_DOMAIN, $WP_SUBDOMAIN.api.$WP_DOMAIN, $WP_SUBDOMAIN.connect.$WP_DOMAIN, *.$WP_DOMAIN"
          
        # Workaround for setting inputs as environmental variables (https://github.com/actions/runner/issues/665#issuecomment-699481628)
        env:
          PROJECT_NAME: ${{ inputs.PROJECT_NAME }}
          GIT_SHA: ${{ inputs.GIT_SHA }}
          GIT_BRANCH: ${{ inputs.GIT_BRANCH }}
          WP_API_VERSION: ${{ inputs.WP_API_VERSION }}
          WP_WEB_VERSION: ${{ inputs.WP_WEB_VERSION }}
          WP_ENVIRONMENT: ${{ inputs.WP_ENVIRONMENT }}
          AWS_ACCESS_KEY_ID_S3: ${{ inputs.AWS_ACCESS_KEY_ID_S3 }}
          WP_DOMAIN: ${{ inputs.WP_DOMAIN }}
          SMTP_USERNAME: ${{ inputs.SMTP_USERNAME }}
          AWS_SECRET_ACCESS_KEY_S3: ${{ secrets.AWS_SECRET_ACCESS_KEY_S3 }}
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          SIDEKIQ_CACHE_PASSWORD: ${{ secrets.SIDEKIQ_CACHE_PASSWORD }}
          FRAGMENT_CACHE_PASSWORD: ${{ secrets.FRAGMENT_CACHE_PASSWORD }}
          FLIPPER_CACHE_PASSWORD: ${{ secrets.FLIPPER_CACHE_PASSWORD }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}

