name: Base Build image

on: 
  workflow_call:
    inputs:
      ECR_REPOSITORY:
        type: string
        required: true
      IMAGE_TAG:
        type: string
        required: true
      API_BASE:
        type: string
        required: true
      SENTRY_ENVIRONMENT:
        type: string
        required: true
      SENTRY_URL:
        type: string
        required: true
      WP_ENVIRONMENT:
        type: string
        required: false
      POSTHOG_HOST:
        type: string
        required: false
      AGENT_BASE:
        type: string
        required: false

    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      FONTAWESOME_TOKEN:
        required: true
      BAUKASTEN_TOKEN:
        required: true
      POSTHOG_KEY:
        required: false

env:
  AWS_DEFAULT_REGION: eu-central-1
  ECR_REGISTRY: 147753604753.dkr.ecr.eu-central-1.amazonaws.com

jobs:
  base_build_image:
    name: Build image
    runs-on: 8-cores
    steps:
      - name: Check out code
        uses: actions/checkout@v5
     
      - uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push image to AWS ECR
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.ECR_REGISTRY }}/${{ inputs.ECR_REPOSITORY }}:${{ inputs.IMAGE_TAG }}
          cache-from: type=registry,ref=${{ env.ECR_REGISTRY }}/${{ inputs.ECR_REPOSITORY }}:cache-${{ inputs.WP_ENVIRONMENT }}
          cache-to: type=registry,mode=max,image-manifest=true,oci-mediatypes=true,ref=${{ env.ECR_REGISTRY }}/${{ inputs.ECR_REPOSITORY }}:cache-${{ inputs.WP_ENVIRONMENT }}
          build-args: |
            FONTAWESOME_TOKEN=${{ secrets.FONTAWESOME_TOKEN }}
            API_BASE=${{ inputs.API_BASE }}
            BAUKASTEN_TOKEN=${{ secrets.BAUKASTEN_TOKEN }}
            POSTHOG_KEY=${{ secrets.POSTHOG_KEY }}
            SENTRY_URL=${{ inputs.SENTRY_URL }}
            SENTRY_ENVIRONMENT=${{ inputs.SENTRY_ENVIRONMENT }}
            POSTHOG_HOST=${{ inputs.POSTHOG_HOST }}
            AGENT_BASE=${{ inputs.AGENT_BASE }}